// I used AI to generate this nodes
export const sampleNodes = [
    { id: 'concept', label: 'Game Concept', connections: ['design', 'story'], url: 'https://www.gamedeveloper.com' },
    { id: 'design', label: 'Game Design', connections: ['mechanics', 'levels'], url: 'https://www.gamedesigning.org' },
    { id: 'story', label: 'Narrative', connections: ['characters', 'dialogue'], url: 'https://www.articy.com' },
    { id: 'mechanics', label: 'Game Mechanics', connections: ['programming'], url: 'https://unity.com' },
    { id: 'levels', label: 'Level Design', connections: ['art', 'programming'], url: 'https://www.unrealengine.com' },
    { id: 'characters', label: 'Character Design', connections: ['art', 'animation'], url: 'https://www.blender.org' },
    { id: 'dialogue', label: 'Dialogue System', connections: ['programming', 'audio'], url: 'https://yarnspinner.dev' },
    { id: 'programming', label: 'Programming', connections: ['engine', 'tools'], url: 'https://docs.unity3d.com/ScriptReference/' },
    { id: 'art', label: 'Art & Graphics', connections: ['modeling', 'textures'], url: 'https://www.adobe.com/products/photoshop.html' },
    { id: 'animation', label: 'Animation', connections: ['rigging', 'vfx'], url: 'https://www.autodesk.com/products/maya/' },
    { id: 'audio', label: 'Audio Design', connections: ['music', 'sfx'], url: 'https://www.reaper.fm' },
    { id: 'engine', label: 'Game Engine', connections: ['testing'], url: 'https://unity.com' },
    { id: 'tools', label: 'Dev Tools', connections: ['testing'], url: 'https://github.com' },
    { id: 'modeling', label: '3D Modeling', connections: ['testing'], url: 'https://www.blender.org' },
    { id: 'textures', label: 'Texturing', connections: ['testing'], url: 'https://www.substance3d.com' },
    { id: 'rigging', label: 'Character Rigging', connections: ['testing'], url: 'https://www.autodesk.com/products/maya/' },
    { id: 'vfx', label: 'Visual Effects', connections: ['testing'], url: 'https://www.aftereffects.com' },
    { id: 'music', label: 'Music Composition', connections: ['testing'], url: 'https://www.image-line.com' },
    { id: 'sfx', label: 'Sound Effects', connections: ['testing'], url: 'https://www.audacityteam.org' },
    { id: 'testing', label: 'QA Testing', connections: ['release'], url: 'https://www.testcomplete.com' },
    { id: 'release', label: 'Release & Distribution', connections: [], url: 'https://store.steampowered.com' },

    { id: 'mobile', label: 'Mobile Development', connections: ['ios', 'android'], url: 'https://developer.android.com/games' },
    { id: 'ios', label: 'iOS Development', connections: ['appstore'], url: 'https://developer.apple.com/games/' },
    { id: 'android', label: 'Android Development', connections: ['playstore'], url: 'https://developer.android.com/games' },
    { id: 'appstore', label: 'App Store', connections: [], url: 'https://developer.apple.com/app-store/' },
    { id: 'playstore', label: 'Google Play', connections: [], url: 'https://play.google.com/console' },

    { id: 'localization', label: 'Localization', connections: [], url: 'https://www.loc.gov' },
    { id: 'accessibility', label: 'Accessibility', connections: [], url: 'https://www.gameaccessibilityguidelines.com' },
    { id: 'esports', label: 'Esports Integration', connections: [], url: 'https://www.esportsearnings.com' },
    { id: 'blockchain', label: 'Blockchain Gaming', connections: [], url: 'https://www.blockchaingamer.biz' },
];